name: build-binpkg

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '6.7.8'
      tag:
        description: 'tag'
        required: true
        default: 'v6.7.8'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - id: cache-webrtc
        uses: actions/cache@v4
        with:
          path: var/cache/binpkgs
          key: tg_owt-0_pre20250515-x86_64-v2-r1

      - name: init
        run: |
          mkdir -p /var/db/repos/gentoo /etc/portage/repos.conf
          emerge-webrsync -q
          cat << EOF > /etc/portage/repos.conf/ayugram.conf
          [ayugram]
          location = ${PWD}
          masters = gentoo
          auto-sync = no
          EOF

      - name: config
        run: |
          cat << 'EOF' >> /etc/portage/make.conf
          COMMON_FLAGS="-march=x86-64-v2 -O2 -pipe"
          CFLAGS="${COMMON_FLAGS}"
          CXXFLAGS="${COMMON_FLAGS}"
          MAKEOPTS="-j2"
          BINPKG_FORMAT="gpkg"
          PKGDIR="${PWD}/var/cache/binpkgs"
          FEATURES="buildpkg getbinpkg -binpkg-request-signature -ipc-sandbox -network-sandbox -pid-sandbox"
          EOF
          mkdir -p /etc/portage/{package.accept_keywords,package.env,package.use,env}
          echo 'COMMON_FLAGS="${COMMON_FLAGS} -fno-lto"' > /etc/portage/env/nolto.conf
          cat << 'EOF' > /etc/portage/package.env/ayugram
          media-libs/tg_owt nolto.conf
          net-im/ayugram-desktop nolto.conf
          EOF
          cat << 'EOF' > /etc/portage/package.use/ayugram
          dev-qt/qtbase opengl
          media-video/ffmpeg vpx opus
          EOF
          cat << EOF > /etc/portage/package.accept_keywords/ayugram
          =media-libs/tg_owt-0_pre20250515* **
          =net-im/ayugram-desktop-${{ inputs.version }} **
          dev-cpp/cppgir **
          EOF
          getuto

      - name: tg_owt
        run: |
          if [ "${{ steps.cache-webrtc.outputs.cache-hit }}" = "true" ]; then
            emerge -1v --usepkgonly media-libs/tg_owt::ayugram
          else
            emerge -1v media-libs/tg_owt::ayugram
          fi

      - name: ayugram
        run: emerge -1v =net-im/ayugram-desktop-${{ inputs.version }}::ayugram

      - name: collect
        run: |
          mkdir -p dist
          find var/cache/binpkgs/net-im/ayugram-desktop -name "*.gpkg.tar" -exec cp -v {} dist/ \;
          chown -R 1001:1001 var/cache/binpkgs dist

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          files: dist/*.gpkg.tar
          fail_on_unmatched_files: true
