name: build-binpkg

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: "6.7.8"
      tag:
        required: true
        default: "v6.7.8"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: gentoo/stage3:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: init
        run: |
          mkdir -p /var/db/repos/gentoo /etc/portage/repos.conf
          emerge-webrsync -q

          cat > /etc/portage/repos.conf/ayugram.conf <<EOF
          [ayugram]
          location = ${PWD}
          masters = gentoo
          auto-sync = no
          EOF

          getuto

      - name: config
        run: |
          cat >> /etc/portage/make.conf <<'EOF'
          COMMON_FLAGS="-march=x86-64-v2 -O2 -pipe"
          CFLAGS="${COMMON_FLAGS}"
          CXXFLAGS="${COMMON_FLAGS}"
          MAKEOPTS="-j2"

          BINPKG_FORMAT="gpkg"
          PKGDIR="${PWD}/var/cache/binpkgs"

          FEATURES="buildpkg getbinpkg -binpkg-request-signature -ipc-sandbox -network-sandbox -pid-sandbox"
          EMERGE_DEFAULT_OPTS="--jobs=2 --with-bdeps=y"
          EOF

          mkdir -p /etc/portage/{package.accept_keywords,package.env,package.use,env}

          echo 'COMMON_FLAGS="${COMMON_FLAGS} -fno-lto"' \
            > /etc/portage/env/nolto.conf

          cat > /etc/portage/package.env/ayugram <<EOF
          media-libs/tg_owt nolto.conf
          net-im/ayugram-desktop nolto.conf
          EOF

          cat > /etc/portage/package.use/ayugram <<EOF
          >=dev-qt/qtbase-6.10.3-r1 opengl icu
          >=media-video/ffmpeg-8.1 opus vpx
          EOF

          cat > /etc/portage/package.accept_keywords/ayugram <<EOF
          =media-libs/tg_owt-0_pre20250515* **
          =net-im/ayugram-desktop-${{ inputs.version }} **
          dev-cpp/cppgir **
          EOF

      - name: build
        run: |
          emerge -1v media-libs/tg_owt::ayugram
          emerge -1v =net-im/ayugram-desktop-${{ inputs.version }}::ayugram

      - name: collect
        run: |
          mkdir -p dist
          find var/cache/binpkgs/net-im/ayugram-desktop \
            -name "*.gpkg.tar" \
            -exec cp {} dist/ \;

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          files: dist/*.gpkg.tar
          fail_on_unmatched_files: true
